<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.168">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Suyeon Hwang">
<meta name="dcterms.date" content="2023-09-18">

<title>Understanding World Population Dynamics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="population-dynamics_files/libs/clipboard/clipboard.min.js"></script>
<script src="population-dynamics_files/libs/quarto-html/quarto.js"></script>
<script src="population-dynamics_files/libs/quarto-html/popper.min.js"></script>
<script src="population-dynamics_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="population-dynamics_files/libs/quarto-html/anchor.min.js"></script>
<link href="population-dynamics_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="population-dynamics_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="population-dynamics_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="population-dynamics_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="population-dynamics_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Understanding World Population Dynamics</h1>
<p class="subtitle lead">Assignment 1 - PSYC593</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Suyeon Hwang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 18, 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<!-- These problems come from Imai, K. & Webb Williams, N. (2018). Quantitative Social Science: An introduction -->
<!-- in tidyverse. Princeton University Press.-->
<!-- The code giving partial solutions by Victor H Cervantes -->
<p>Understanding population dynamics is important for many areas of social science. We will calculate some basic demographic quantities of births and deaths for the world’s population from two time periods: 1950 to 1955 and 2005 to 2010. We will analyze the following CSV data files - <code>Kenya.csv</code>, <code>Sweden.csv</code>, and <code>World.csv</code>. Each file contains population data for Kenya, Sweden, and the world, respectively. The table below presents the names and descriptions of the variables in each data set.</p>
<div class="cell">

</div>
<table class="table">
<colgroup>
<col style="width: 36%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>country</code></td>
<td style="text-align: left;">Abbreviated country name</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>period</code></td>
<td style="text-align: left;">Period during which data are collected</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>age</code></td>
<td style="text-align: left;">Age group</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>births</code></td>
<td style="text-align: left;">Number of births in thousands (i.e., number of children born to women of the age group)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>deaths</code></td>
<td style="text-align: left;">Number of deaths in thousands</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>py.men</code></td>
<td style="text-align: left;">Person-years for men iW thousands</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>py.women</code></td>
<td style="text-align: left;">Person-years for women in thousands</td>
</tr>
</tbody>
</table>
<p>Source: United Nations, Department of Economic and Social Affairs, Population Division (2013). <em>World Population Prospects: The 2012 Revision, DVD Edition.</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load packages ----</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here) <span class="co"># This package is used to help with paths</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Path variables ----</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>here_path <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>() <span class="co"># Just using here for finding root path directories. It follows additional heuristics</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Some of the subdirectories</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>code_path <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"src"</span>) <span class="co"># Using the base R function file.path</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>docs_path <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"doc"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>data_path <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>figs_path <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"results"</span>, <span class="st">"figures"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read data ----</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>world_data  <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="at">file =</span> <span class="fu">file.path</span>(data_path, <span class="st">"raw_data"</span>, <span class="st">"World.csv"</span>), <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>kenya_data  <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="at">file =</span> <span class="fu">file.path</span>(data_path, <span class="st">"raw_data"</span>,<span class="st">"Kenya.csv"</span>), <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>sweden_data <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="at">file =</span> <span class="fu">file.path</span>(data_path, <span class="st">"raw_data"</span>,<span class="st">"Sweden.csv"</span>), <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<!-- The `read_csv` function from the package `readr` -->
<!-- is part of the `tidyverse`. It will read the data into a -->
<!-- special `data.frame` with more structure known as a `tibble` -->
<p>The data are collected for a period of 5 years where <em>person-year</em> is a measure of the time contribution of each person during the period. For example, a person that lives through the entire 5 year period contributes 5 person-years whereas someone who only lives through the first half of the period contributes 2.5 person-years. Before you begin this exercise, it would be a good idea to directly inspect each data set. In R, this can be done with the <code>View</code> function, which takes as its argument the name of a <code>data.frame</code> to be examined. Alternatively, in RStudio, double-clicking a <code>data.frame</code> in the <code>Environment</code> tab will enable you to view the data in a spreadsheet-like view.</p>
<section id="question-1" class="level2">
<h2 class="anchored" data-anchor-id="question-1">Question 1</h2>
<p>We begin by computing <em>crude birth rate</em> (CBR) for a given period. The CBR is defined as: <span class="math display">\[
    \text{CBR}
     =  \frac{\text{number of births}}{\text{number of person-years lived}}
  \]</span> <!-- It is also possible to include $\LaTeX$ syntax directly in the document. --></p>
<p>Compute the CBR for each period, separately for Kenya, Sweden, and the world. Start by computing the total person-years, recorded as a new variable within each existing <code>data.frame</code> via the <code>$</code> operator, by summing the person-years for men and women. Then, store the results as a vector of length 2 (CBRs for two periods) for each region with appropriate labels. You may wish to create your own function for the purpose of efficient programming. Briefly describe patterns you observe in the resulting CBRs.</p>
<section id="answer-1" class="level3">
<h3 class="anchored" data-anchor-id="answer-1">Answer 1</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create new variable py = total person years for each data set</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>world_data<span class="sc">$</span>py <span class="ot">&lt;-</span> world_data<span class="sc">$</span>py.men <span class="sc">+</span> world_data<span class="sc">$</span>py.women</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>kenya_data<span class="sc">$</span>py <span class="ot">&lt;-</span> kenya_data<span class="sc">$</span>py.men <span class="sc">+</span> kenya_data<span class="sc">$</span>py.women</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>sweden_data<span class="sc">$</span>py <span class="ot">&lt;-</span> sweden_data<span class="sc">$</span>py.men <span class="sc">+</span> sweden_data<span class="sc">$</span>py.women</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<!-- Whenever you find that you will repeat the same calculation -->
<!-- on different sets of data, **consider** creating a function -->
<!-- instead of repeating the code for each piece of data. -->
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to compute the Crude Birth Rate (CBR)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>compute_cbr <span class="ot">&lt;-</span> <span class="cf">function</span> (pop_data) {</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  pop_data<span class="sc">%&gt;%</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(period) <span class="sc">%&gt;%</span> </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">summarise</span>(<span class="at">cbr =</span> <span class="fu">sum</span>(births) <span class="sc">/</span> <span class="fu">sum</span>(py)) <span class="sc">%&gt;%</span> </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">pull</span>()</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<!-- The "pipe" `%>%` from package `magrittr` takes the output -->
<!-- from the left hand side and makes it the first argument of -->
<!-- the expression on the right hand side. -->
<!-- Starting in R 4.1.0, there is a base pipe operator `|>` -->
<!-- which has a similar behavior. -->
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the CBR for each data set</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>(worldcbr  <span class="ot">&lt;-</span><span class="fu">compute_cbr</span>(world_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03732863 0.02021593</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>(kenyacbr  <span class="ot">&lt;-</span><span class="fu">compute_cbr</span>(kenya_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05209490 0.03851507</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>(swedencbr <span class="ot">&lt;-</span><span class="fu">compute_cbr</span>(sweden_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01539614 0.01192554</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to create a table of the data of CBR </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>compute_cbr <span class="ot">&lt;-</span> <span class="cf">function</span> (populationData) {</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  populationData <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(period) <span class="sc">%&gt;%</span> </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">summarise</span>(<span class="at">cbr =</span> <span class="fu">sum</span>(births) <span class="sc">/</span> <span class="fu">sum</span>(py)) <span class="sc">%&gt;%</span> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">pull</span>()</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Region</th>
<th style="text-align: left;">1950-1955</th>
<th style="text-align: left;">2005-2010</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">World</td>
<td style="text-align: left;">0.03732863</td>
<td style="text-align: left;">0.02021593</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kenya</td>
<td style="text-align: left;">0.05209490</td>
<td style="text-align: left;">0.03851507</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sweden</td>
<td style="text-align: left;">0.01539614</td>
<td style="text-align: left;">0.01192554</td>
</tr>
</tbody>
</table>
<p>There seems to be a decline of CBR overall from 1950-1955 to 2005-2010. There seems to be a decline of CBR overall from 1950-1955 to 2005-2010. The world data is in a similar trend to both Kenya and Sweden. Kenya’s CBR seems to be higher than the world’s average, whereas Sweden’s CBR seems to lower than the world’s average.</p>
</section>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<p>The CBR is easy to understand but contains both men and women of all ages in the denominator. We next calculate the <em>total fertility rate</em> (TFR). Unlike the CBR, the TFR adjusts for age compositions in the female population. To do this, we need to first calculate the <em>age specific fertility rate</em> (ASFR), which represents the fertility rate for women of the reproductive age range <span class="math inline">\([15, 50)\)</span>. The ASFR for age range <span class="math inline">\([x, x+\delta)\)</span>, where <span class="math inline">\(x\)</span> is the starting age and <span class="math inline">\(\delta\)</span> is the width of the age range (measured in years), is defined as: <span class="math display">\[
    \text{ASFR}_{[x,\ x+\delta)}
    \ = \ \frac{\text{number of births to women of age $[x,\ x+\delta)$}}{\text{Number of person-years lived by women of age $[x,\ x+\delta)$}}
  \]</span> Note that square brackets, <span class="math inline">\([\)</span> and <span class="math inline">\(]\)</span>, include the limit whereas parentheses, <span class="math inline">\((\)</span> and <span class="math inline">\()\)</span>, exclude it. For example, <span class="math inline">\([20, 25)\)</span> represents the age range that is greater than or equal to 20 years old and less than 25 years old. In typical demographic data, the age range <span class="math inline">\(\delta\)</span> is set to 5 years. Compute the ASFR for Sweden and Kenya as well as the entire world for each of the two periods. Store the resulting ASFRs separately for each region. What does the pattern of these ASFRs say about reproduction among women in Sweden and Kenya?</p>
<section id="answer-2" class="level3">
<h3 class="anchored" data-anchor-id="answer-2">Answer 2</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to compute Age specific fertility rate (ASFR)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>compute_asfr <span class="ot">&lt;-</span> <span class="cf">function</span> (pop_data) {</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  pop_data <span class="sc">%&gt;%</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">asfr =</span> births <span class="sc">/</span> py.women)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute ASFR for each data set</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>world_data  <span class="ot">&lt;-</span> <span class="fu">compute_asfr</span>(world_data)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>kenya_data  <span class="ot">&lt;-</span> <span class="fu">compute_asfr</span>(kenya_data)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>sweden_data <span class="ot">&lt;-</span> <span class="fu">compute_asfr</span>(sweden_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare ASFRs for Kenya and Sweden</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>kenya_data<span class="sc">$</span>asfr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.00000000 0.00000000 0.00000000 0.16884585 0.35596942 0.34657814
 [7] 0.28946367 0.20644016 0.11193267 0.03905205 0.00000000 0.00000000
[13] 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000
[19] 0.10057087 0.23583536 0.23294721 0.18087964 0.13126805 0.05626214
[25] 0.03815044 0.00000000 0.00000000 0.00000000 0.00000000 0.00000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>sweden_data<span class="sc">$</span>asfr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.0000000000 0.0000000000 0.0000000000 0.0389089519 0.1277108826
 [6] 0.1252436647 0.0873641591 0.0486037714 0.0162101857 0.0013418290
[11] 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000
[16] 0.0000000000 0.0000000000 0.0000000000 0.0059709097 0.0507320271
[21] 0.1162085625 0.1322744621 0.0625923991 0.0121600765 0.0006143942
[26] 0.0000000000 0.0000000000 0.0000000000 0.0000000000 0.0000000000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create Bar Chart: specify variables</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"0-4"</span>, <span class="st">"5-9"</span>, <span class="st">"10-14"</span>, <span class="st">"15-19"</span>, <span class="st">"20-24"</span>, <span class="st">"25-39"</span>, <span class="st">"40-44"</span>, <span class="st">"45-49"</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>         <span class="st">"50-54"</span>, <span class="st">"55-59"</span>, <span class="st">"60-64"</span>, <span class="st">"65-69"</span>, <span class="st">"70-74"</span>, <span class="st">"75-79"</span>, <span class="st">"80+"</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>asfr_total <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(kenya_data<span class="sc">$</span>asfr[<span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>], kenya_data<span class="sc">$</span>asfr[<span class="dv">16</span><span class="sc">:</span><span class="dv">30</span>], </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                      sweden_data<span class="sc">$</span>asfr[<span class="dv">1</span><span class="sc">:</span><span class="dv">15</span>], sweden_data<span class="sc">$</span>asfr[<span class="dv">16</span><span class="sc">:</span><span class="dv">30</span>]),</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nrow =</span> <span class="dv">4</span>, <span class="at">ncol =</span> <span class="dv">15</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>regions <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Kenya (1950-1955)"</span>, <span class="st">"Kenya (2005-2010)"</span>, </span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>             <span class="st">"Sweden (1950-1955)"</span>, <span class="st">"Sweden (2005-2010)"</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'steelblue'</span>, <span class="st">'orange'</span>, <span class="st">'brown'</span>, <span class="st">'purple'</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a><span class="co"># create bar plot</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(asfr_total, <span class="at">main =</span> <span class="st">"ASFR for Kenya and Sweden"</span>, <span class="at">names.arg =</span> age, </span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>                          <span class="at">xlab =</span> <span class="st">"Age"</span>, <span class="at">ylab =</span> <span class="st">"ASFR"</span>, </span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>                          <span class="at">col =</span> colors, <span class="at">beside =</span> <span class="cn">TRUE</span>, <span class="at">cex.names=</span><span class="fl">0.5</span>)</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the legend to the chart</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, regions, <span class="at">cex =</span> <span class="dv">1</span>, <span class="at">fill =</span> colors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="population-dynamics_files/figure-html/bar%20chart2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Kenya’s ASFR is much higher than Sweden’s, and again, there’s a decline when the two periods are compared for both Kenya and Sweden. The age 15-59 seems to be when women reproduce, with the ASFR being highest for age 20-24 for Kenya, whereas age 25-29 seems to be slightly higher for Sweden.</p>
</section>
</section>
<section id="question-3" class="level2">
<h2 class="anchored" data-anchor-id="question-3">Question 3</h2>
<p>Using the ASFR, we can define the TFR as the average number of children women give birth to if they live through their entire reproductive age. <span class="math display">\[
  \text{TFR}
   =   \text{ASFR}_{[15,\ 20)} \times 5 + \text{ASFR}_{[20,\ 25)} \times 5
  + \dots + \text{ASFR}_{[45,\ 50)} \times 5
  \]</span></p>
<p>We multiply each age-specific fertility rate rate by 5 because the age range is 5 years. Compute the TFR for Sweden and Kenya as well as the entire world for each of the two periods. As in the previous question, continue to assume that women’s reproductive age range is <span class="math inline">\([15, 50)\)</span>. Store the resulting two TFRs for each country or the world as a vector of length two. In general, how has the number of women changed in the world from 1950 to 2000? What about the total number of births in the world?</p>
<section id="answer-3" class="level3">
<h3 class="anchored" data-anchor-id="answer-3">Answer 3</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to compute the total fertility rate (TFR)</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>compute_tfr <span class="ot">&lt;-</span> <span class="cf">function</span> (pop_data) {</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  pop_data <span class="sc">%&gt;%</span> </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(period) <span class="sc">%&gt;%</span> </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">summarise</span>(<span class="at">tfr =</span> <span class="dv">5</span> <span class="sc">*</span><span class="fu">sum</span>(asfr)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>        <span class="fu">pull</span>()</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the TFR for each data set</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>(world_tfr  <span class="ot">&lt;-</span> <span class="fu">compute_tfr</span>(world_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.007248 2.543623</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>(kenya_tfr  <span class="ot">&lt;-</span> <span class="fu">compute_tfr</span>(kenya_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.591410 4.879568</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>(sweden_tfr <span class="ot">&lt;-</span> <span class="fu">compute_tfr</span>(sweden_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.226917 1.902764</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute totals of women and births in the world by period</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>world_data <span class="sc">%&gt;%</span> </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(period) <span class="sc">%&gt;%</span> </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_women =</span> <span class="fu">sum</span>(py.women), </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">total_births =</span> <span class="fu">sum</span>(births)) </span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="ot">-&gt;</span> totals_world</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 x 3
  period    total_women total_births
  &lt;chr&gt;           &lt;dbl&gt;        &lt;dbl&gt;
1 1950-1955    6555686.      488892.
2 2005-2010   16554781.      674581.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare how much these totals have changed</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>(changes_totals <span class="ot">&lt;-</span> totals_world[<span class="dv">2</span>,<span class="sc">-</span><span class="dv">1</span>] <span class="sc">/</span> totals_world[<span class="dv">1</span>,<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  total_women total_births
1    2.525256     1.379818</code></pre>
</div>
</div>
<p>While the total fertility rate has dropped almost half from 1950-1955 to 2005-2010, it seems that the total women have increased from 1950-1955 to 2005-2010, from around 6.55 million to 15.65 million.</p>
<p>Again, Kenya is higher than the world and Sweden is lower than the world for all the computed numbers.</p>
<p>The number of total births have also increased, from 488,891 to 674,581 total births. Thus the total women population have increased by 250%, whereas the total births have increased by 137%.</p>
</section>
</section>
<section id="question-4" class="level2">
<h2 class="anchored" data-anchor-id="question-4">Question 4</h2>
<p>Next, we will examine another important demographic process: death. Compute the <em>crude death rate</em> (CDR), which is a concept analogous to the CBR, for each period and separately for each region. Store the resulting CDRs for each country and the world as a vector of length two. The CDR is defined as: <span class="math display">\[
    \text{CDR}
     =  \frac{\text{number of deaths}}{\text{number of person-years lived}}
  \]</span> Briefly describe patterns you observe in the resulting CDRs.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to compute the Crude death rate (CDR)</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>compute_cdr <span class="ot">&lt;-</span> <span class="cf">function</span> (pop_data) {</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  pop_data <span class="sc">%&gt;%</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(period) <span class="sc">%&gt;%</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">summarise</span>(<span class="at">cbr =</span> <span class="fu">sum</span>(deaths) <span class="sc">/</span> <span class="fu">sum</span>(py)) <span class="sc">%&gt;%</span> </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">pull</span>()</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the CDR for each data set</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>(world_cdr  <span class="ot">&lt;-</span> <span class="fu">compute_cdr</span>(world_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.019318929 0.008166083</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>(kenya_cdr  <span class="ot">&lt;-</span> <span class="fu">compute_cdr</span>(kenya_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02396254 0.01038914</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>(sweden_cdr <span class="ot">&lt;-</span> <span class="fu">compute_cdr</span>(sweden_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.009844842 0.009968455</code></pre>
</div>
</div>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Region</th>
<th style="text-align: left;">1950-1955</th>
<th style="text-align: left;">2005-2010</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">World</td>
<td style="text-align: left;">0.019318929</td>
<td style="text-align: left;">0.008166083</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kenya</td>
<td style="text-align: left;">0.02396254</td>
<td style="text-align: left;">0.01038914</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sweden</td>
<td style="text-align: left;">0.009844842</td>
<td style="text-align: left;">0.009968455</td>
</tr>
</tbody>
</table>
<p>From the chart we see that the there’s a decrease of CDR from 1950-1955 to 2005-2010. The world’s CDR is the lowest, followed by Sweden, with the highest being Kenya. Kenya’s CDR is almost twice Sweden’s CDR for 1950-1955, though this number becomes almost about the same for 2005-2010.</p>
</section>
<section id="question-5" class="level2">
<h2 class="anchored" data-anchor-id="question-5">Question 5</h2>
<p>One puzzling finding from the previous question is that the CDR for Kenya during the period of 2005-2010 is about the same level as that for Sweden. We would expect people in developed countries like Sweden to have a lower death rate than those in developing countries like Kenya. While it is simple and easy to understand, the CDR does not take into account the age composition of a population. We therefore compute the <em>age specific death rate</em> (ASDR). The ASDR for age range <span class="math inline">\([x, x+\delta)\)</span> is defined as: <span class="math display">\[
    \text{ASDR}_{[x,\ x+\delta)}
    \ = \ \frac{\text{number of deaths for people of age $[x,\ x+\delta)$}}
               {\text{number of person-years of people of age $[x,\ x+\delta)$}}
  \]</span> Calculate the ASDR for each age group, separately for Kenya and Sweden, during the period of 2005-2010. Briefly describe the pattern you observe.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to compute Age specific death rate (ASDR)</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>compute_asdr <span class="ot">&lt;-</span> <span class="cf">function</span> (pop_data) {</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  pop_data <span class="sc">%&gt;%</span> </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">asdr =</span> deaths <span class="sc">/</span> py) <span class="sc">%&gt;%</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>()</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute ASDR for each data set</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>(world_asdr  <span class="ot">&lt;-</span> <span class="fu">compute_asdr</span>(world_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.054589755 0.005600412 0.004261869 0.004752908 0.005891020 0.006325420
 [7] 0.007132501 0.008534487 0.010572557 0.013459846 0.017335769 0.024265320
[13] 0.042262017 0.086910343 0.184364978 0.012802492 0.001256903 0.001079067
[19] 0.001302818 0.001832602 0.002278500 0.002623982 0.003031563 0.003753402
[25] 0.005085583 0.007126588 0.010477192 0.020235894 0.047457519 0.120679385</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>(kenya_asdr  <span class="ot">&lt;-</span> <span class="fu">compute_asdr</span>(kenya_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.066826532 0.009321789 0.005972093 0.005869582 0.007651103 0.008838750
 [7] 0.009677594 0.010986891 0.012633744 0.014760408 0.018260395 0.024433007
[13] 0.041996801 0.093683927 0.200016381 0.020920755 0.002911301 0.002918895
[19] 0.002942986 0.003885368 0.006558131 0.010603913 0.013881062 0.013474598
[25] 0.011288057 0.011152339 0.013898334 0.025395531 0.061261551 0.158620510</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>(sweden_asdr <span class="ot">&lt;-</span> <span class="fu">compute_asdr</span>(sweden_data))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 4.745670e-03 4.320537e-04 4.896406e-04 7.431865e-04 1.017734e-03
 [6] 1.114091e-03 1.334385e-03 1.742949e-03 2.509554e-03 3.966876e-03
[11] 6.348641e-03 1.016728e-02 2.141566e-02 5.998231e-02 1.678170e-01
[16] 6.790712e-04 8.138094e-05 1.135496e-04 2.687775e-04 4.697344e-04
[21] 4.941440e-04 5.057066e-04 6.689578e-04 1.039256e-03 1.769621e-03
[26] 2.988715e-03 4.709913e-03 9.828772e-03 2.803963e-02 1.098892e-01</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create Bar Chart: specify variables</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"0-4"</span>, <span class="st">"5-9"</span>, <span class="st">"10-14"</span>, <span class="st">"15-19"</span>, <span class="st">"20-24"</span>, <span class="st">"25-39"</span>, <span class="st">"40-44"</span>, <span class="st">"45-49"</span>,</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>         <span class="st">"50-54"</span>, <span class="st">"55-59"</span>, <span class="st">"60-64"</span>, <span class="st">"65-69"</span>, <span class="st">"70-74"</span>, <span class="st">"75-79"</span>, <span class="st">"80+"</span>)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>asdr_total <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(kenya_asdr[<span class="dv">16</span><span class="sc">:</span><span class="dv">30</span>], sweden_asdr[<span class="dv">16</span><span class="sc">:</span><span class="dv">30</span>]),</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">ncol =</span> <span class="dv">15</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>regions <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Kenya"</span>, <span class="st">"Sweden"</span>)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'steelblue'</span>, <span class="st">'orange'</span>)</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a><span class="co"># create bar plot</span></span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(asdr_total, <span class="at">main =</span> <span class="st">"ASDR for Kenya and Sweden in 2005-2010"</span>, <span class="at">names.arg =</span> age, </span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>                          <span class="at">xlab =</span> <span class="st">"Age"</span>, <span class="at">ylab =</span> <span class="st">"ASDR"</span>, </span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>                          <span class="at">col =</span> colors, <span class="at">beside =</span> <span class="cn">TRUE</span>, <span class="at">cex.names=</span><span class="fl">0.5</span>)</span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the legend to the chart</span></span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, regions, <span class="at">cex =</span> <span class="dv">1</span>, <span class="at">fill =</span> colors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="population-dynamics_files/figure-html/bar%20chart-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When we take into account the age specific composition of the population, we see that Kenya’s ASDR is higher than for Sweden’s ASDR, over all age, suggesting that perhaps Sweden had a higher number of population who were more likely to die during 2005-2010.</p>
</section>
<section id="question-6" class="level2">
<h2 class="anchored" data-anchor-id="question-6">Question 6</h2>
<p>One way to understand the difference in the CDR between Kenya and Sweden is to compute the counterfactual CDR for Kenya using Sweden’s population distribution (or vice versa). This can be done by applying the following alternative formula for the CDR. <span class="math display">\[
    \text{CDR}
    \ = \ \text{ASDR}_{[0, 5)} \times P_{[0,5)} + \text{ASDR}_{[5, 10)}
    \times P_{[5, 10)} + \cdots
  \]</span> where <span class="math inline">\(P_{[x, x+\delta)}\)</span> is the proportion of the population in the age range <span class="math inline">\([x, x+\delta)\)</span>. We compute this as the ratio of person-years in that age range relative to the total person-years across all age ranges. To conduct this counterfactual analysis, we use <span class="math inline">\(\text{ASDR}_{[x,x+\delta)}\)</span> from Kenya and <span class="math inline">\(P_{[x,x+\delta)}\)</span> from Sweden during the period of 2005–2010. That is, first calculate the age-specific population proportions for Sweden and then use them to compute the counterfactual CDR for Kenya. How does this counterfactual CDR compare with the original CDR of Kenya? Briefly interpret the result.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to compute population proportion by period</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>compute_pop_prop <span class="ot">&lt;-</span> <span class="cf">function</span> (pop_data) {</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  pop_data <span class="sc">%&gt;%</span> </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(period) <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">pop_prop =</span> py <span class="sc">/</span> <span class="fu">sum</span>(py)) <span class="sc">%&gt;%</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">pull</span>()</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute population proportion for each data set</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>world_pop_prop <span class="ot">&lt;-</span> <span class="fu">compute_pop_prop</span>(world_data)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>kenya_pop_prop <span class="ot">&lt;-</span> <span class="fu">compute_pop_prop</span>(kenya_data)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>sweden_pop_prop <span class="ot">&lt;-</span> <span class="fu">compute_pop_prop</span>(sweden_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute Kenyas CDR Kenya had to Sweden's population distribution</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(kenya_data,</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">temp_cdr =</span> kenya_asdr <span class="sc">*</span> sweden_pop_prop) <span class="sc">%&gt;%</span></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">group_by</span>(period) <span class="sc">%&gt;%</span></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarise</span>(<span class="at">cdrresweden =</span> <span class="fu">sum</span>(temp_cdr))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 x 2
  period    cdrresweden
  &lt;chr&gt;           &lt;dbl&gt;
1 1950-1955      0.0257
2 2005-2010      0.0232</code></pre>
</div>
</div>
<p>The CDR for Kenya was 0.01038914, whereas when we compute Kenya’s CDR to Sweden’s population distribution, such that we have a counterfactual CDR, it turns out to be 0.02321646. Thus if Kenya had the population proportion similar to Sweden, then the CDR turns out to be much higher. Therefore, we can infer that Sweden’s popululation tends to have a higher proportion of people vulnerable to death.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>